export enum EnviromentVariablesEnum {
    PORT = 'PORT',
    ENABLE_CORS = 'ENABLE_CORS',
    ENABLE_DOCS = 'ENABLE_DOCS',
    NOSQL_CONNECTION_STRING = 'NOSQL_CONNECTION_STRING',
    JWT_KEY = 'JWT_KEY',
    JWT_REFRESH_TOKEN_KEY = 'JWT_REFRESH_TOKEN_KEY',
    JWT_REFRESH_TOKEN_EXPIRATION = 'JWT_REFRESH_TOKEN_EXPIRATION',
    JWT_ACCESS_TOKEN_EXPIRATION = 'JWT_ACCESS_TOKEN_EXPIRATION',
    ENCRYPT_KEY = 'ENCRYPT_KEY',

    SENDGRID_EMAIL_SENDER = 'SENDGRID_EMAIL_SENDER',
    SENDGRID_API_KEY = 'SENDGRID_API_KEY',

    BUCKET = 'BUCKET',
}