export enum EnviromentVariablesEnum {
    PORT = 'PORT',
    ENABLE_CORS = 'ENABLE_CORS',
    ENABLE_DOCS = 'ENABLE_DOCS',
    NOSQL_CONNECTION_STRING = 'NOSQL_CONNECTION_STRING',
    JWT_KEY = 'JWT_KEY',
    JWT_REFRESH_TOKEN_KEY = 'JWT_REFRESH_TOKEN_KEY',
    JWT_REFRESH_TOKEN_EXPIRATION = 'JWT_REFRESH_TOKEN_EXPIRATION',
    JWT_ACCESS_TOKEN_EXPIRATION = 'JWT_ACCESS_TOKEN_EXPIRATION',
    ENCRYPT_KEY = 'ENCRYPT_KEY',
    SENDGRID_EMAIL_SENDER = 'SENDGRID_EMAIL_SENDER',
    SENDGRID_API_KEY = 'SENDGRID_API_KEY',
    AWS_REGION = 'AWS_REGION',
    AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
    AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
    S3_BUCKET = 'S3_BUCKET',
    SMS_API_URL = 'SMS_API_URL',
    SMS_API_TOKEN='SMS_API_TOKEN'
}