export enum EnviromentVariablesEnum {
    PORT = 'PORT',
    ENABLE_CORS = 'ENABLE_CORS',
    ENABLE_DOCS = 'ENABLE_DOCS',
    NOSQL_CONNECTION_STRING = 'NOSQL_CONNECTION_STRING',
    JWT_KEY = 'JWT_KEY',
    JWT_REFRESH_TOKEN_KEY = 'JWT_REFRESH_TOKEN_KEY',
    JWT_REFRESH_TOKEN_EXPIRATION = 'JWT_REFRESH_TOKEN_EXPIRATION',
    JWT_ACCESS_TOKEN_EXPIRATION = 'JWT_ACCESS_TOKEN_EXPIRATION',
    ENCRYPT_KEY = 'ENCRYPT_KEY',

    ZI_TOKEN_ADDRESS = 'ZI_TOKEN_ADDRESS',
    BUSD_TOKEN_ADDRESS = 'BUSD_TOKEN_ADDRESS',
    USDT_TOKEN_ADDRESS = 'USDT_TOKEN_ADDRESS',

    POLYGON_NETWORK = 'POLYGON_NETWORK',
    ETHEREUM_NETWORK = 'ETHEREUM_NETWORK',
    INFURA_PROJECT_ID = 'INFURA_PROJECT_ID',
    SENDGRID_EMAIL_SENDER = 'SENDGRID_EMAIL_SENDER',
    SENDGRID_API_KEY = 'SENDGRID_API_KEY',

    BINANCE_API = 'BINANCE_API',

    HOT_WALLET = 'HOT_WALLET',

    BINANCE_SMART_CHAIN_NETWORK = 'BINANCE_SMART_CHAIN_NETWORK',

    OBSERVABLE_API = 'OBSERVABLE_API',

    AWS_REGION = 'AWS_REGION',
    AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
    AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
    S3_BUCKET = 'S3_BUCKET',

    GECKO_API = 'GECKO_API',

    SWAP_WALLET = 'SWAP_WALLET',
    SWAP_MNEUMONIC = 'SWAP_MNEUMONIC',

    SMS_API_URL = 'SMS_API_URL',
    SMS_API_TOKEN = 'SMS_API_TOKEN',

    ASAAS_API_KEY = 'ASAAS_API_KEY',
    ASAAS_PIX_KEY = 'ASAAS_PIX_KEY',
    ASAAS_ENDPOINT = 'ASAAS_ENDPOINT',

    POLYGON_SCAN = 'POLYGON_SCAN',
    ETHEREUM_SCAN = 'ETHEREUM_SCAN',
    BSC_SCAN = 'BSC_SCAN',

    COIN_GECKO_URL = 'COIN_GECKO_URL'
}